# Generated by Django 3.0.2 on 2020-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvestmouseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestedmouse',
            name='physicalId',
            field=models.TextField(unique=True),
        ),
    ]
